config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/#{I18n.default_locale}/articles")

  scope "/:locale" do
    get "/about", to: "about#index", as: :about
    resources :articles
    resources :projects
    devise_for :users
  end
  # Health Check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :featured_image
  has_one_attached :thumbnail

  enum :category, { uncategorized: 0, coding: 1, game_development: 2, gaming: 3, lifestyle: 4 }
  enum :status, { draft: 0, published: 1 }

  validates :headline, presence: true
  validates :subtitle, presence: true
  validates :text, presence: true
  validates :category, presence: true
  validates :status, presence: true

  after_commit :set_published_at, on: [ :create, :update ], if: :article_published?

  private

  def article_published?
    saved_change_to_status? && published?
  end

  def set_published_at
    update_column(:published_at, Time.now)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :icon
  enum status: { unpublished: 0, published: 1 }
  enum category: { software: 0, game: 1, web: 2, other: 3 }
  enum programming_language: { ruby_on_rails: 0, c_sharp: 1, javascript: 2, python: 3, java: 4 }

  validates :title, presence: true
  validates :description, presence: true
  validates :url, presence: true
  validates :status, presence: true
  validates :category, presence: true
  validates :programming_language, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    params[:category] ||= "coding"
    @articles = Article.where(category: params[:category]).order(created_at: :desc)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_nav_link(path)
    if current_page?(path)
      "text-sky-500 w-full h-6 flex items-center justify-center relative after:absolute after:w-0.5 after:right-0 after:top-0 after:bottom-0 after:bg-sky-500"
    else
      "text-slate-400 hover:text-slate-500 dark:text-slate-500 dark:hover:text-slate-400 w-full h-6 flex items-center justify-center"
    end
  end

  def active_category_link(active_category, category)
    if active_category == category
      "block py-3 font-medium text-slate-800 dark:text-slate-100 border-b-2 border-sky-500"
    else
      "block py-3 font-medium text-slate-800 dark:text-slate-100"
    end
  end

  def active_locale_icon(locale)
    case locale
    when :da
      asset_path("da.svg")
    when :en
      asset_path("en.svg")
    else
      asset_path("en.svg")
    end
  end

  def swap_locale(locale)
    case locale
    when :da
      I18n.locale = :en
    when :en
      I18n.locale = :da
    else
      I18n.locale = :en
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/partials/_role.html.erb
<li class="relative py-2">
  <div class="flex items-start mb-1">
    <div class="absolute left-0 h-full w-px bg-slate-200 dark:bg-slate-800 self-start ml-[28px] -translate-x-1/2 translate-y-3" aria-hidden="true"></div>
    <div class="absolute left-0 h-14 w-14 flex items-center justify-center border border-slate-200 dark:border-slate-800 dark:bg-gradient-to-t dark:from-slate-800 dark:to-slate-800/30 bg-white dark:bg-slate-900 rounded-full">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
        <path fill="#DE4D3B" d="M15.912 6.545h-7.75v3.273h4.393c-.702 2.182-2.437 2.91-4.428 2.91-2.12.002-3.992-1.368-4.601-3.37a4.693 4.693 0 0 1 1.959-5.307 4.854 4.854 0 0 1 5.722.33l2.414-2.265C10.947-.31 6.964-.69 3.867 1.186.771 3.06-.683 6.735.308 10.18c.99 3.445 4.185 5.822 7.819 5.82 4.477 0 8.525-2.91 7.785-9.456Z" />
      </svg>
    </div>
    <div class="pl-20 space-y-1">
      <div class="text-xs text-slate-500 uppercase">May 2020 <span class="text-slate-400 dark:text-slate-600">·</span> Present</div>
      <div class="font-aspekta font-[650] text-slate-800 dark:text-slate-100"><%= role.position %></div>
      <div class="text-sm font-medium text-slate-800 dark:text-slate-100"><%= role.company %></div>
      <div class="text-sm text-slate-500 dark:text-slate-400"><%= role.description %></div>
    </div>
  </div>
</li>

app/views/articles/index.html.erb
<!-- Hero -->
<section>
  <div class="max-w-[700px]">
    <div class="pt-8 pb-10">
      <%= image_tag asset_path('profile-picture.jpg'), class: 'rounded-full mb-5', width: '56', height: '56', alt: 'Me' %>
      <h1 class="h1 font-aspekta mb-5"><%= t('views.articles.index.introduction.header_html') %></h1>
      <p class="text-lg text-slate-500 dark:text-slate-400"><%= t('views.articles.index.introduction.header_text') %></p>
    </div>
  </div>
</section>

<!-- Content -->
<div class="grow md:flex space-y-8 md:space-y-0 md:space-x-8 pb-16 md:pb-20">
  <!-- Middle area -->
  <div class="grow">
    <div class="max-w-[700px]">
      <div class="space-y-10">
        <!-- Latest Articles -->
        <section>
          <h2 class="font-aspekta text-xl font-[650] mb-3"><%= t('views.articles.index.articles.header') %></h2>

          <!-- Filters -->
          <ul class="flex flex-wrap text-sm border-b border-slate-100 dark:border-slate-800">
            <% Article.categories&.each do |category, value| %>
              <% if category.to_s != 'uncategorized' %>
                <li class="px-3 -mb-px">
                  <%= link_to category.to_s.titleize, articles_path(category: category, locale: params[:locale]), class: active_category_link(category, params[:category]), data: { turbo_frame: 'article_list', turbo_action: 'replace' } %>
                </li>
              <% end %>
            <% end %>
          </ul>

          <!-- Articles list -->
          <%= turbo_frame_tag 'article_list' if @articles.present? do %>
            <div>
              <% @articles.published.sort_by{ |e| e.published_at }.reverse.each do |article| %>
                <%= render 'articles/partials/article', article: article %>
              <% end %>
            </div>
          <% end %>
        </section>
        <!-- Projects -->
        <section>
          <h2 class="font-aspekta text-xl font-[650] mb-5"><%= t('views.articles.index.projects.header') %></h2>
          
          <!-- Cards -->
          <div class="grid sm:grid-cols-2 md:grid-cols-1 lg:grid-cols-2 gap-5">
            <%= link_to 'https://github.com/NikoDyring/personal_portfolio', class:"rounded-lg border border-slate-200 dark:border-slate-800 dark:bg-gradient-to-t dark:from-slate-800 dark:to-slate-800/30 odd:-rotate-1 even:rotate-1 hover:rotate-0 transition-transform duration-700 hover:duration-100 ease-in-out p-5" do %>
              <div class="flex flex-col h-full">
                <div class="grow">
                  <div class="h-10 w-10 flex items-center justify-center border border-slate-200 dark:border-slate-700 rounded-full mb-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18">
                      <path fill="#34D399" fill-rule="evenodd" d="M9.97 14.758c-.018 1.796-.497 3.248-1.072 3.242-.574-.006-1.026-1.466-1.008-3.262.017-1.796.497-3.247 1.071-3.242.575.006 1.026 1.466 1.009 3.262Zm-3.332-.408c-.977 1.502-2.16 2.461-2.64 2.143-.48-.318-.076-1.793.902-3.294.977-1.501 2.159-2.46 2.64-2.143.48.318.076 1.793-.902 3.294Zm-2.687-2.154c-1.628.73-3.137.893-3.37.364-.233-.53.897-1.55 2.524-2.28 1.628-.73 3.136-.893 3.37-.363.233.529-.897 1.55-2.524 2.28Zm2.328-3.764c-.087.573-1.585.815-3.346.542-1.76-.273-3.116-.959-3.029-1.531.087-.573 1.585-.815 3.346-.542 1.76.273 3.117.959 3.03 1.531Zm.632-1.363c-.38.434-1.77-.179-3.105-1.368C2.57 4.51 1.798 3.195 2.178 2.76c.38-.434 1.77.179 3.106 1.368C6.618 5.32 7.392 6.635 7.01 7.07Zm1.26-.797c-.554.157-1.395-1.116-1.88-2.844C5.906 1.7 5.961.17 6.514.013c.553-.158 1.394 1.116 1.879 2.844.485 1.728.43 3.257-.123 3.415Zm3.417-2.79C11.17 5.2 10.304 6.456 9.754 6.287c-.55-.168-.575-1.698-.056-3.416.519-1.718 1.385-2.974 1.934-2.806.55.169.575 1.698.056 3.417Zm2.443 2.321c-1.358 1.163-2.76 1.748-3.132 1.307-.372-.442.427-1.742 1.785-2.905 1.357-1.163 2.76-1.748 3.131-1.306.372.441-.427 1.742-1.784 2.904Zm.807 3.286c-1.765.238-3.258-.034-3.334-.608-.077-.575 1.293-1.233 3.058-1.471 1.766-.238 3.259.034 3.335.608.076.574-1.293 1.233-3.059 1.47Zm2.278 3.635c-.244.525-1.75.332-3.362-.43-1.613-.762-2.723-1.806-2.48-2.33.245-.525 1.75-.332 3.363.43s2.722 1.806 2.479 2.33Zm-3.393 3.87c-.486.308-1.65-.674-2.597-2.195-.948-1.52-1.323-3.003-.836-3.311.486-.308 1.649.674 2.597 2.195.948 1.52 1.322 3.003.836 3.31Z" />
                    </svg>
                  </div>
                  <div class="text-lg font-aspekta font-[650] mb-1">Personal Portfolio</div>
                  <p class="text-sm text-slate-500 dark:text-slate-400 mb-2">This portfolio built with Rails, Tailwindcss and a PostgreSQL database. Hosted on DigitalOcean.</p>
                </div>
                <div class="text-sky-500 flex justify-end">
                  <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="14" height="12">
                    <path d="M9.586 5 6.293 1.707 7.707.293 13.414 6l-5.707 5.707-1.414-1.414L9.586 7H0V5h9.586Z" />
                  </svg>
                </div>
              </div>
            <% end %>
            <%= link_to 'https://github.com/NikoDyring/sidelinehq', class: "rounded-lg border border-slate-200 dark:border-slate-800 dark:bg-gradient-to-t dark:from-slate-800 dark:to-slate-800/30 odd:-rotate-1 even:rotate-1 hover:rotate-0 transition-transform duration-700 hover:duration-100 ease-in-out p-5" do %>
              <div class="flex flex-col h-full">
                <div class="grow">
                  <div class="h-10 w-10 flex items-center justify-center border border-slate-200 dark:border-slate-700 rounded-full mb-2">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18">
                      <path fill="#4db623ff" fill-rule="evenodd" d="M3.849 1.619a9.052 9.052 0 0 0-1.732 1.582c2.066-.192 4.69.12 7.735 1.644 3.253 1.626 5.873 1.681 7.696 1.33a8.95 8.95 0 0 0-.62-1.44c-2.087.22-4.763-.071-7.88-1.63-1.98-.99-3.726-1.398-5.2-1.486ZM15.709 3A8.977 8.977 0 0 0 9 0c-.783 0-1.542.1-2.266.288.98.267 2.022.659 3.118 1.207C12.135 2.636 14.106 3.004 15.708 3Zm2.228 4.933c-2.202.435-5.243.345-8.89-1.478C5.639 4.75 2.926 4.772 1.096 5.179a9.117 9.117 0 0 0-.276.066A8.933 8.933 0 0 0 .25 6.883c.146-.04.298-.077.454-.112 2.22-.493 5.357-.472 9.147 1.424 3.41 1.704 6.123 1.683 7.953 1.276l.185-.043a9.133 9.133 0 0 0-.053-1.495Zm-.24 3.395c-2.182.38-5.134.234-8.65-1.523C5.639 8.1 2.926 8.122 1.096 8.529c-.406.09-.771.2-1.094.316L0 9a9 9 0 0 0 17.696 2.328Z" />
                    </svg>
                  </div>
                  <div class="text-lg font-aspekta font-[650] mb-1">SidelineHQ</div>
                  <p class="text-sm text-slate-500 dark:text-slate-400 mb-2">Early-stage project focused on building powerful tools for coaches and players. Make fun and engaging through gamification. </p>
                </div>
                <div class="text-sky-500 flex justify-end">
                  <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="14" height="12">
                    <path d="M9.586 5 6.293 1.707 7.707.293 13.414 6l-5.707 5.707-1.414-1.414L9.586 7H0V5h9.586Z" />
                  </svg>
                </div>
              </div>
            <% end %>
          </div>
        </section>
      </div>
    </div>
  </div>
  <%= render 'articles/partials/right_sidebar' %>
</div>

app/views/articles/partials/_article.html.erb
<article class="py-5 border-b border-slate-100 dark:border-slate-800">
  <div class="flex items-start">
    <%#= image_tag article.thumbnail, class: 'rounded w-16 h-16 sm:w-[88px] sm:h-[88px] object-cover mr-6', width: '88', height: '88', alt: article.headline %>
    <div>
      <div class="text-xs text-slate-500 uppercase mb-1"><span class="text-sky-500">—</span> <%= article.published_at.strftime("#{article.published_at.day.ordinalize} %B %Y") %></div>
      <h3 class="font-aspekta text-lg font-[650] mb-1">
        <%= link_to article.headline, article_path(article, locale: I18n.locale), class: 'inline-flex relative hover:text-sky-500 duration-150 ease-out before:scale-x-0 before:origin-center before:absolute before:inset-0 before:bg-sky-200 dark:before:bg-sky-500 before:opacity-30 before:-z-10 before:translate-y-1/4 before:-rotate-2 hover:before:scale-100 before:duration-150 before:ease-in-out' %>
      </h3>
      <div class="flex">
        <div class="grow text-sm text-slate-500 dark:text-slate-400">
          <%= article.subtitle %>
        </div>
        <%= link_to article_path(article, locale: I18n.locale), class: 'hidden lg:flex shrink-0 text-sky-500 items-center justify-center w-12 group' do %>
          <svg class="fill-current group-hover:translate-x-2 duration-150 ease-in-out" xmlns="http://www.w3.org/2000/svg" width="14" height="12">
            <path d="M9.586 5 6.293 1.707 7.707.293 13.414 6l-5.707 5.707-1.414-1.414L9.586 7H0V5h9.586Z" />
          </svg>
        <% end %>
      </div>
    </div>
  </div>
</article>

app/views/articles/partials/_footer.html.erb
<!-- Footer -->
<footer class="border-t border-slate-200 dark:border-slate-800">
  <div class="py-8">
    <div class="text-center md:flex md:items-center md:justify-between">

      <!-- Social links -->
      <ul class="inline-flex mb-4 md:order-1 md:ml-4 md:mb-0 space-x-2">
        <li>
          <%= link_to 'https://twitter.com/nikodyring', class: 'flex justify-center items-center text-sky-500 hover:text-sky-600 transition duration-150 ease-in-out', 'aria-label': 'Twitter', target: '_blank' do %>
            <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
              <path d="M24 11.5c-.6.3-1.2.4-1.9.5.7-.4 1.2-1 1.4-1.8-.6.4-1.3.6-2.1.8-.6-.6-1.5-1-2.4-1-1.7 0-3.2 1.5-3.2 3.3 0 .3 0 .5.1.7-2.7-.1-5.2-1.4-6.8-3.4-.3.5-.4 1-.4 1.7 0 1.1.6 2.1 1.5 2.7-.5 0-1-.2-1.5-.4 0 1.6 1.1 2.9 2.6 3.2-.3.1-.6.1-.9.1-.2 0-.4 0-.6-.1.4 1.3 1.6 2.3 3.1 2.3-1.1.9-2.5 1.4-4.1 1.4H8c1.5.9 3.2 1.5 5 1.5 6 0 9.3-5 9.3-9.3v-.4c.7-.5 1.3-1.1 1.7-1.8z" />
            </svg>
          <% end %>
        </li>
        <li>
          <%= link_to 'https://youtube.com/zakecss', class: 'flex justify-center items-center text-sky-500 hover:text-sky-600 transition duration-150 ease-in-out', 'aria-label': 'YouTube', target: '_blank' do %>
            <svg class="w-8 h-8 fill-current" viewBox=" 0 0 32 32" xmlns="http://www.w3.org/2000/svg">
              <path d="M23.8 12.8c-.2-1.3-.8-2.2-2.2-2.4C19.4 10 16 10 16 10s-3.4 0-5.6.4c-1.4.2-2.1 1.1-2.2 2.4C8 14.1 8 16 8 16s0 1.9.2 3.2c.2 1.3.8 2.2 2.2 2.4 2.2.4 5.6.4 5.6.4s3.4 0 5.6-.4c1.4-.3 2-1.1 2.2-2.4.2-1.3.2-3.2.2-3.2s0-1.9-.2-3.2ZM14 19v-6l5 3-5 3Z" />
            </svg>
          <% end %>
        </li>
        <li>
          <%= link_to 'https://github.com/NikoDyring', class: 'flex justify-center items-center text-sky-500 hover:text-sky-600 transition duration-150 ease-in-out', 'aria-label':'GitHub', target: '_blank' do %>
            <svg class="w-8 h-8 fill-current" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
              <path d="M16 8.2c-4.4 0-8 3.6-8 8 0 3.5 2.3 6.5 5.5 7.6.4.1.5-.2.5-.4V22c-2.2.5-2.7-1-2.7-1-.4-.9-.9-1.2-.9-1.2-.7-.5.1-.5.1-.5.8.1 1.2.8 1.2.8.7 1.3 1.9.9 2.3.7.1-.5.3-.9.5-1.1-1.8-.2-3.6-.9-3.6-4 0-.9.3-1.6.8-2.1-.1-.2-.4-1 .1-2.1 0 0 .7-.2 2.2.8.6-.2 1.3-.3 2-.3s1.4.1 2 .3c1.5-1 2.2-.8 2.2-.8.4 1.1.2 1.9.1 2.1.5.6.8 1.3.8 2.1 0 3.1-1.9 3.7-3.7 3.9.3.4.6.9.6 1.6v2.2c0 .2.1.5.6.4 3.2-1.1 5.5-4.1 5.5-7.6-.1-4.4-3.7-8-8.1-8z" />
            </svg>
          <% end %>
        </li>
      </ul>

      <!-- Copyright -->
      <div class="text-sm text-slate-500 dark:text-slate-400 inline">
        © 2023 <%= link_to 'NikoDyring.dev', 'https://github.com/nikodyring' %> - All rights reserved. | Built with
        <%= link_to 'https://rubyonrails.org/' do %>
          <%= image_tag(asset_path('ruby-on-rails.svg'), class: 'inline-block', width: 60, height: 30) %>
        <% end %>
      </div>
    </div>
  </div>
</footer>

app/views/articles/partials/_right_sidebar.html.erb
<!-- Right sidebar -->
<aside class="md:w-[240px] lg:w-[300px] shrink-0">
  <div class="space-y-6">
    <%#= render 'articles/partials/right_sidebar/newlsetter' %>
    <%#= render 'articles/partials/right_sidebar/sponsor' %>
    <%#= render 'articles/partials/right_sidebar/ebook' %>
  </div>
</aside>

app/views/articles/partials/right_sidebar/_ebook.html.erb
<!-- E-Book widget -->
<div class="rounded-lg border border-slate-200 dark:border-slate-800 dark:bg-gradient-to-t dark:from-slate-800 dark:to-slate-800/30 odd:rotate-1 even:-rotate-1 p-5">
  <div class="font-aspekta font-[650] text-center mb-3">Free E-Book</div>
  <div class="text-center">
    <%# <%= image_tag "book.png", class: "inline-flex rounded-lg shadow-lg rotate-3", width: "148", height: "190", alt: "Book" %> %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nikolaj Dyring - RoR Developer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script>
        if (localStorage.getItem('dark-mode') === 'false' || !('dark-mode' in localStorage)) {
            document.querySelector('html').classList.remove('dark');
        } else {
            document.querySelector('html').classList.add('dark');
        }
    </script>
  </head>

  <body class="font-inter antialiased bg-white text-slate-800 dark:bg-slate-900 dark:text-slate-200 tracking-tight">
    <div class="max-w-7xl mx-auto">
      <div class="min-h-screen flex">
        <%= render 'partials/sidebar' %>
        <main class="grow overflow-hidden px-6">
          <div class="w-full h-full max-w-[1072px] mx-auto flex flex-col">
            <%= render 'partials/header' %>
            <%= yield %>
            <%= render 'articles/partials/footer' %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<div class="sticky top-0 w-16 md:w-24 shrink-0 h-screen overflow-y-auto no-scrollbar border-r border-slate-200 dark:border-slate-800">
  <div class="h-full flex flex-col justify-between after:flex-1 after:mt-auto">
    <div class="flex-1"></div>
    <div class="flex-1 grow flex items-center">
      <nav class="w-full">
        <ul class="space-y-4">
          <li class="py-2">
            <%= link_to articles_path(locale: I18n.locale), class: active_nav_link(articles_path(locale: I18n.locale)) do %>
              <span class="sr-only">Home</span>
              <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="21" height="19">
                <path fill-opacity=".16" d="M4 7v11h13V7l-6.5-5z" />'
                <path d="m10.433 3.242-8.837 6.56L.404 8.198l10.02-7.44L20.59 8.194l-1.18 1.614-8.977-6.565ZM16 17V9h2v10H3V9h2v8h11Z" />
              </svg>
            <% end %>
          </li>
          <li class="py-2">
            <%= link_to about_path(locale: I18n.locale), class: active_nav_link(about_path(locale: I18n.locale)) do %>
              <span class="sr-only">About</span>
              <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="20" height="20">
                <path fill-opacity=".16" d="M10 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8Z" />
                <path d="M9 5h2v2H9V5Zm0 4h2v6H9V9Zm1-9C4.48 0 0 4.48 0 10s4.48 10 10 10 10-4.48 10-10S15.52 0 10 0Zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8Z" />
              </svg>
            <% end %>
          </li>
<!--          <li class="py-2">-->
            <%#= link_to projects_path(locale: I18n.locale), class: active_nav_link(projects_path(locale: I18n.locale)) do %>
<!--              <span class="sr-only">Projects</span>-->
<!--              <svg class="fill-current" width="20" height="20" xmlns="http://www.w3.org/2000/svg">-->
<!--                <path d='M8.18 15.008c.12 0 .211-.004.271-.012a.317.317 0 0 0 .18-.107c.06-.063.09-.154.09-.274l-.004-.557c-.003-.355-.004-.637-.004-.844l-.188.033a2.41 2.41 0 0 1-.455.028 3.498 3.498 0 0 1-.57-.057 1.276 1.276 0 0 1-.548-.246 1.04 1.04 0 0 1-.36-.503l-.082-.189a2.046 2.046 0 0 0-.258-.417.989.989 0 0 0-.357-.312l-.057-.04a.602.602 0 0 1-.106-.1.455.455 0 0 1-.074-.114c-.016-.038-.003-.07.04-.094a.533.533 0 0 1 .238-.037l.164.025c.11.021.245.087.406.196.16.11.293.251.397.426.126.224.277.395.455.512a.964.964 0 0 0 .536.176c.18 0 .336-.013.467-.04a1.63 1.63 0 0 0 .369-.124c.049-.365.182-.647.4-.843a5.61 5.61 0 0 1-.839-.148 3.346 3.346 0 0 1-.77-.32 2.204 2.204 0 0 1-.66-.548c-.174-.219-.317-.505-.43-.86a4.09 4.09 0 0 1-.167-1.229c0-.66.216-1.223.647-1.687-.202-.497-.183-1.054.057-1.671.159-.05.394-.013.705.11.311.123.54.228.684.316.145.087.26.16.348.22a5.814 5.814 0 0 1 1.573-.212c.54 0 1.065.07 1.573.213l.31-.197c.214-.13.465-.251.754-.36.29-.11.511-.14.664-.09.246.617.268 1.174.065 1.67.432.465.648 1.027.648 1.688 0 .464-.056.875-.168 1.233-.112.358-.257.644-.434.86a2.29 2.29 0 0 1-.664.545 3.342 3.342 0 0 1-.77.32 5.605 5.605 0 0 1-.84.147c.284.245.426.633.426 1.163v1.957c0 .093.014.168.041.226a.226.226 0 0 0 .131.119c.06.021.114.035.16.04.047.006.113.009.2.009h-1.966-2.227z'/>-->
<!--                <path d='M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16zm0 2C4.477 20 0 15.523 0 10S4.477 0 10 0s10 4.477 10 10-4.477 10-10 10z'/>-->
<!--              </svg>-->
            <%# end %>
<!--          </li>-->
<!--          <li class="py-2">-->
<!--            <a class="text-slate-400 hover:text-slate-500 dark:text-slate-500 dark:hover:text-slate-400 w-full h-6 flex items-center justify-center" href="subscribe.html">-->
<!--              <span class="sr-only">Subscribe</span>-->
<!--              <svg class="fill-current" xmlns="http://www.w3.org/2000/svg" width="21" height="21">-->
<!--                <path fill-opacity=".16" d="m13.4 18-3-7.4-7.4-3L19 2z" />-->
<!--                <path d="M13.331 15.169 17.37 3.63 5.831 7.669l5.337 2.163 2.163 5.337Zm-3.699-3.801L.17 7.53 20.63.37l-7.161 20.461-3.837-9.463Z" />-->
<!--              </svg>-->
<!--            </a>-->
<!--          </li>-->
        </ul>
      </nav>
    </div>
  </div>
</div>